### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by rakeen** [Mimieam/Sublime-Maze#4]
I've ST3 installed in -> C:\Program Files\Sublime Text 3\Packages   and
the user data are stored in  ->  C:\Users\rak1\AppData\Roaming\Sublime Text 3\Packages

I've copied the repository in ...\AppData\Roaming\Sublime Text 3\Packages  but I think there's some problem with the directory structure.

![image](https://cloud.githubusercontent.com/assets/10359412/7371315/e7c87a2e-ede1-11e4-9ba5-a781f4ac3b98.png)

**Comment by Mimieam** [comment]
Hey @rakeen, sorry for the (ridiculous) delay, I had stopped the development of this plugin due to a weird view bug that is now fix in ST3.

anyway, a quick fix for this error would be to modify the  `Maze(Windows).sublime-settings` file
from 
 `  "color_scheme": "Packages/Walker/syntax/maze-theme.hidden-tmTheme" ` 
to 
`C:\Users\rak1\AppData\Roaming\Sublime Text 3\Packages\Walker\syntax\maze-theme.hidden-tmTheme`
